# src/fastlane/Fastfile
default_platform(:ios)

platform :ios do
  desc "Build iOS app for personal development"
  lane :build_dev do
    build_app(
      workspace: "#{ENV['APP_NAME']}.xcworkspace",
      scheme: "#{ENV['APP_NAME']}",
      clean: true,
      configuration: "Debug",
      output_directory: "./build",
      output_name: "#{ENV['APP_NAME']}.ipa",
      include_symbols: true,
      skip_profile_detection: true,
      xcargs: "-allowProvisioningUpdates",
      export_options: {
        method: "development",
        signing_style: "automatic",
        compile_bitcode: false,
        team_id: ENV["TEAM_ID"]
      },
      
    )
  end

  desc "Build release iOS app"
  lane :build do    
    update_project_team(
      path: "#{ENV['APP_NAME']}.xcodeproj",
      teamid: ENV["TEAM_ID"]
    )
    
    gym(
      workspace: "#{ENV['APP_NAME']}.xcworkspace",
      scheme: "#{ENV['APP_NAME']}",
      clean: true,
      configuration: "Release",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "#{ENV['APP_NAME']}.ipa",
      include_bitcode: false,
      include_symbols: true,
      export_options: {
        method: "app-store",
        signing_style: "automatic", 
        team_id: ENV["TEAM_ID"]
      },
      xcargs: "-allowProvisioningUpdates"
    )
  end
end

platform :android do
  desc "Build Android app"
  lane :build do
    build_app(
      project: "#{ENV['APP_NAME']}.aab"
    )
  end
end
